# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f699d2fc4c4fe36a119112b369ed119348a1b477297a07dcf22b4be4331e1ceeac0f7119efe3b68f614186105cda6629ae2f243815aa4a7f5ccc0cc5c24b89

test:
  secret_key_base: afdb61039d54d9b23f6f8290295a7d2311a4b7ee009c53a51f2b30acade12995070f4d1250ff59a702bae84db4c1bcad439a9abe2598900d1b76a0e6773e2453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
